// Auto-generated. Do not edit!

// (in-package my_robot_tut3.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class Navigate2DResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.elasped_time = null;
    }
    else {
      if (initObj.hasOwnProperty('elasped_time')) {
        this.elasped_time = initObj.elasped_time
      }
      else {
        this.elasped_time = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type Navigate2DResult
    // Serialize message field [elasped_time]
    bufferOffset = _serializer.float32(obj.elasped_time, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type Navigate2DResult
    let len;
    let data = new Navigate2DResult(null);
    // Deserialize message field [elasped_time]
    data.elasped_time = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_tut3/Navigate2DResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'db081717cf33b98580276ae311236046';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Result
    float32 elasped_time
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new Navigate2DResult(null);
    if (msg.elasped_time !== undefined) {
      resolved.elasped_time = msg.elasped_time;
    }
    else {
      resolved.elasped_time = 0.0
    }

    return resolved;
    }
};

module.exports = Navigate2DResult;
