(cl:defpackage my_robot_tut3-msg
  (:use )
  (:export
   "<NAVIGATE2DACTION>"
   "NAVIGATE2DACTION"
   "<NAVIGATE2DACTIONFEEDBACK>"
   "NAVIGATE2DACTIONFEEDBACK"
   "<NAVIGATE2DACTIONGOAL>"
   "NAVIGATE2DACTIONGOAL"
   "<NAVIGATE2DACTIONRESULT>"
   "NAVIGATE2DACTIONRESULT"
   "<NAVIGATE2DFEEDBACK>"
   "NAVIGATE2DFEEDBACK"
   "<NAVIGATE2DGOAL>"
   "NAVIGATE2DGOAL"
   "<NAVIGATE2DRESULT>"
   "NAVIGATE2DRESULT"
  ))

