; Auto-generated. Do not edit!


(cl:in-package my_robot_tut3-msg)


;//! \htmlinclude Navigate2DResult.msg.html

(cl:defclass <Navigate2DResult> (roslisp-msg-protocol:ros-message)
  ((elasped_time
    :reader elasped_time
    :initarg :elasped_time
    :type cl:float
    :initform 0.0))
)

(cl:defclass Navigate2DResult (<Navigate2DResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Navigate2DResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Navigate2DResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_tut3-msg:<Navigate2DResult> is deprecated: use my_robot_tut3-msg:Navigate2DResult instead.")))

(cl:ensure-generic-function 'elasped_time-val :lambda-list '(m))
(cl:defmethod elasped_time-val ((m <Navigate2DResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_tut3-msg:elasped_time-val is deprecated.  Use my_robot_tut3-msg:elasped_time instead.")
  (elasped_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Navigate2DResult>) ostream)
  "Serializes a message object of type '<Navigate2DResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'elasped_time))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Navigate2DResult>) istream)
  "Deserializes a message object of type '<Navigate2DResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'elasped_time) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Navigate2DResult>)))
  "Returns string type for a message object of type '<Navigate2DResult>"
  "my_robot_tut3/Navigate2DResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Navigate2DResult)))
  "Returns string type for a message object of type 'Navigate2DResult"
  "my_robot_tut3/Navigate2DResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Navigate2DResult>)))
  "Returns md5sum for a message object of type '<Navigate2DResult>"
  "db081717cf33b98580276ae311236046")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Navigate2DResult)))
  "Returns md5sum for a message object of type 'Navigate2DResult"
  "db081717cf33b98580276ae311236046")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Navigate2DResult>)))
  "Returns full string definition for message of type '<Navigate2DResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%float32 elasped_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Navigate2DResult)))
  "Returns full string definition for message of type 'Navigate2DResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Result~%float32 elasped_time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Navigate2DResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Navigate2DResult>))
  "Converts a ROS message object to a list"
  (cl:list 'Navigate2DResult
    (cl:cons ':elasped_time (elasped_time msg))
))
