(cl:defpackage my_robot_tut3-srv
  (:use )
  (:export
   "ODDEVENCHECK"
   "<ODDEVENCHECK-REQUEST>"
   "ODDEVENCHECK-REQUEST"
   "<ODDEVENCHECK-RESPONSE>"
   "ODDEVENCHECK-RESPONSE"
   "TURNCAMERA"
   "<TURNCAMERA-REQUEST>"
   "TURNCAMERA-REQUEST"
   "<TURNCAMERA-RESPONSE>"
   "TURNCAMERA-RESPONSE"
  ))

