// Generated by gencpp from file my_robot_tut3/OddEvenCheck.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_TUT3_MESSAGE_ODDEVENCHECK_H
#define MY_ROBOT_TUT3_MESSAGE_ODDEVENCHECK_H

#include <ros/service_traits.h>


#include <my_robot_tut3/OddEvenCheckRequest.h>
#include <my_robot_tut3/OddEvenCheckResponse.h>


namespace my_robot_tut3
{

struct OddEvenCheck
{

typedef OddEvenCheckRequest Request;
typedef OddEvenCheckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OddEvenCheck
} // namespace my_robot_tut3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_tut3::OddEvenCheck > {
  static const char* value()
  {
    return "4ff0b0ab1ed04611e3a2b4090af9ee4f";
  }

  static const char* value(const ::my_robot_tut3::OddEvenCheck&) { return value(); }
};

template<>
struct DataType< ::my_robot_tut3::OddEvenCheck > {
  static const char* value()
  {
    return "my_robot_tut3/OddEvenCheck";
  }

  static const char* value(const ::my_robot_tut3::OddEvenCheck&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_tut3::OddEvenCheckRequest> should match
// service_traits::MD5Sum< ::my_robot_tut3::OddEvenCheck >
template<>
struct MD5Sum< ::my_robot_tut3::OddEvenCheckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_tut3::OddEvenCheck >::value();
  }
  static const char* value(const ::my_robot_tut3::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_tut3::OddEvenCheckRequest> should match
// service_traits::DataType< ::my_robot_tut3::OddEvenCheck >
template<>
struct DataType< ::my_robot_tut3::OddEvenCheckRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_tut3::OddEvenCheck >::value();
  }
  static const char* value(const ::my_robot_tut3::OddEvenCheckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_tut3::OddEvenCheckResponse> should match
// service_traits::MD5Sum< ::my_robot_tut3::OddEvenCheck >
template<>
struct MD5Sum< ::my_robot_tut3::OddEvenCheckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_tut3::OddEvenCheck >::value();
  }
  static const char* value(const ::my_robot_tut3::OddEvenCheckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_tut3::OddEvenCheckResponse> should match
// service_traits::DataType< ::my_robot_tut3::OddEvenCheck >
template<>
struct DataType< ::my_robot_tut3::OddEvenCheckResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_tut3::OddEvenCheck >::value();
  }
  static const char* value(const ::my_robot_tut3::OddEvenCheckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_TUT3_MESSAGE_ODDEVENCHECK_H
